---
kind: pipeline
type: exec
name: bM2

clone:
  retries: 3

platform:
  os: darwin
  arch: arm64

steps:
- name: Test
  commands:
    - echo "Hello world!"

- name: Build
  commands:
    - echo "Hello world!"
  depends_on:
  - Test

---
kind: pipeline
type: exec
name: Build on Linux

clone:
  retries: 3

platform:
  os: darwin
  arch: arm64

steps:
- name: Test
  commands:
    - echo "Hello world!"

- name: Build
  commands:
    - echo "Hello world!"
  depends_on:
  - Test

---
kind: pipeline
type: exec
name: Publish

clone:
  retries: 3

platform:
  os: darwin
  arch: arm64

- name: Publish
  commands:
    - echo "Hello world!"
    
depends_on:
- bM2