---
kind: pipeline
type: exec
name: Build on macOS (M2)

clone:
  retries: 3

platform:
  os: darwin
  arch: arm64

steps:
- name: Build
  commands:
   - node --version
   - npm --version
   - yarn --version