---
kind: pipeline
type: exec
name: Build on macOS

clone:
  retries: 3

platform:
  os: darwin
  arch: arm64

steps:
- name: Build
  commands:
    - yarn install
    - yarn run build

    - mv dist/Penpot\ Desktop*.dmg dist/Penpot.dmg
    - mv dist/Penpot\ Desktop*.zip dist/Penpot.zip