---
kind: pipeline
type: exec
name: Build on Windows

clone:
  retries: 3

platform:
  os: darwin
  arch: arm64

- name: Build
  commands:
    - yarn
    - yarn build

    - mv dist/Penpot\ Desktop*.dmg dist/Penpot.dmg
    - mv dist/Penpot\ Desktop*.zip dist/Penpot.zip