---
kind: pipeline
type: exec
name: Test on macOS (M2)

clone:
  retries: 3

platform:
  os: darwin
  arch: arm64

steps:
- name: Test
  commands:
    - echo "Hello world!

---
kind: pipeline
type: exec
name: Build on macOS (M2)

clone:
  retries: 3

platform:
  os: darwin
  arch: arm64

steps:
- name: Build
  commands:
    - echo "Hello world!"
  when:
    status:
    - success