name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: mac
    steps:
      - run: |
     cd /Users/korbsstudio/Documents/gitea-actions/
     git clone https://sudovanilla.com/code/Korbs/Penpot-Desktop
     cd Penpot-Desktop
     yarn
     yarn bulid