name: test
run-name: test
on: [push]

jobs:
  build:
    runs-on: mac
    steps:
      - run: cd /Users/korbsstudio/Documents/gitea-actions/
      - run: git clone https://sudovanilla.com/code/Korbs/Penpot-Desktop && cd Penpot-Desktop
      - run: ls
      - run: yarn