Prepare:
  tags:
    - main
  stage: .pre
  only:
    - main
  script:
    - if [ -d "dist/" ]; then rm -R dist/; fi # Delete the dist/ folder if it exist
    - export $(grep -v '^#' .env | xargs)
    - mkdir /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/$VERSION/

# Build
Windows:
  tags:
    - main
  stage: build
  only:
    - production
  script:
    - yarn
    - yarn build:win
    - cp dist/Penpot*.exe /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/.prepare/
    - cp dist/latest.yml /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/.prepare/

Mac:
  variables:
    GIT_STRATEGY: none # Due to OS being isolated in a VM in certain conditions, conflicts will rise
  tags:
    - mac
  stage: build
  only:
    - main
  script:
    - echo "Hi, I'm a Mac."
    - sleep 2
    - cd /Users/korbs/Documents/
    - cd Penpot-Desktop
    - git checkout main
    - git pull
    - yarn
    - yarn build
    - mv dist/Penpot*.dmg dist/Penpot.dmg
    - lftp -u $SFTP_USERNAME,$SFTP_PASSWORD $SFTP_IP -e "set ftp:ssl-allow off; cd /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/.prepare/; put dist/Penpot.dmg; bye;"

Linux:
  tags:
    - main
  stage: build
  only:
    - production
  script:
    - yarn
    - yarn build
    - cp dist/*.deb /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/.prepare/
    - cp dist/*.rpm /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/.prepare/

# Deploy
Windows-Ready:
  tags:
    - main
  stage: deploy
  only:
    - production
  needs:
    - job: Prepare
    - job: Windows
  script:
    - cd /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/.prepare/
    - cp Penpot*.exe /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/latest/
    - cp latest.yml /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/latest/
    - cp Penpot*.exe /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/$VERSION/

Mac-Ready:
  tags:
    - main
  stage: deploy
  only:
    - main
  needs:
    - job: Mac
  dependencies: 
    - Mac
  script:
    - cd /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/.prepare/
    - cp Penpot.dmg /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/latest/
    - cp Penpot.dmg /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/$VERSION/

Linux-Ready:
  tags:
    - main
  stage: deploy
  only:
    - production
  needs:
    - job: Prepare
    - job: Linux
  script:
    - cd /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/.prepare/
    - cloudsmith push rpm korbsstudio/penpot-desktop/any-distro/any-version *.rpm --api-key="$CSK"
    - cloudsmith push deb korbsstudio/penpot-desktop/any-distro/any-version *.deb --api-key="$CSK"
    - sleep 24
    - rm /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/.prepare/*