Prepare:
  stage: .pre
  only:
    - main
  script:
      - echo "Prepare"
    # - export $(grep -v '^#' .env | xargs)
    # - mkdir /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/$VERSION/

Windows:
  tags:
    - WindowsVM
  stage: build
  artifacts:
     paths:
       - README.md
  only:
    - main
  script:
    - echo "Get dependencies"
    - echo "Check dist/ directory"
    - echo "Run build"
    - sleep 2

Linux:
  stage: build
  only:
    - main
  script:
    - echo "Get dependencies"
    - echo "Check dist/ directory"
    - echo "Run build"
    - sleep 24
    - ls
    - ls *

Windows-Ready:
  stage: deploy
  only:
    - main
  needs:
    - Prepare
  script:
    - echo "Prepare to upload..."
    - echo "Upload files to main server..."
    - echo "Remove dist/ folder for future builds."

Linux-Ready:
  stage: deploy
  only:
    - main
  needs:
    - Prepare
    - Linux
    - Windows # We need to grab an artifact from Windows :)
  script:
    - echo "Prepare to upload..."
    - echo "Upload packages to Cloudsmith..."
    - echo "Remove dist/ folder for future builds."
    - sleep 5
    - echo "Download artifact from Windows (Latest)..."
    - cd
    - sleep 1
    - wget "https://korbsstudio.com/code/KorbsStudio/Penpot-Desktop/-/jobs/artifacts/main/download?job=Windows"
    - sleep 1
    - ls
    - sleep 1