Prepare:
  stage: .pre
  only:
    - main
  script:
      - "Prepare"
    # - export $(grep -v '^#' .env | xargs)
    # - mkdir /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/$VERSION/

Windows:
  tags:
    - WindowsVM
  stage: build
  only:
    - main
  script:
    - echo "Get dependencies"
    - echo "Check dist/ directory"
    - echo "Run build"

Linux:
  stage: build
  only:
    - main
  script:
    - echo "Get dependencies"
    - echo "Check dist/ directory"
    - echo "Run build"

Windows-Ready:
  stage: deploy
  only:
    - main
  needs:
    - Prepare
  script:
    - echo "Prepare to upload..."
    - echo "Upload files to main server..."
    - echo "Remove dist/ folder for future builds."

Linux-Ready:
  stage: deploy
  only:
    - main
  needs:
    - Prepare
    - Linux
  script:
    - echo "Prepare to upload..."
    - echo "Upload package to Cloudsmith..."
    - echo "Remove dist/ folder for future builds."
