# exe:
#   stage: build
#   script:
#     - echo "Do your build here"

deb:
  tags:
    - debian
  stage: build
  script:
    - echo "Get dependencies"
    - sleep 5
    - ecgo "Check dist/ directory"
    - sleep 2
    - echo "Run build"
    - sleep 10

rpm:
  stage: build
  script:
    - echo "Get dependencies"
    - sleep 5
    - ecgo "Check dist/ directory"
    - sleep 2
    - echo "Run build"
    - sleep 10

debready:
  stage: deploy
  script:
    - echo "Prepare to upload..."
    - sleep 2
    - echo "Upload package to Cloudsmith..."
    - sleep 10
    - echo "Remove dist/ folder for future builds."
    - sleep 1

rpmready:
  stage: deploy
  script:
    - echo "Prepare to upload..."
    - sleep 2
    - echo "Upload package to Cloudsmith..."
    - sleep 10
    - echo "Remove dist/ folder for future builds."
    - sleep 1