Prepare:
  tags:
    - main
  stage: .pre
  only:
    - production
  script:
    - export $(grep -v '^#' .env | xargs)
    - mkdir /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/$VERSION/

# Build
Windows:
  tags:
    - WindowsVM
  stage: build
  artifacts:
     paths:
       - dist/
  only:
    - production
  script:
    - yarn
    - yarn build
    - Remove-Item -path .\dist\win-unpacked\ -recurse  # This will make sure that the artifact doesn't take a butt load of time to zip up the dist folder I need

Linux:
  tags:
    - main
  stage: build
  only:
    - production
  script:
    - if [ -d "dist/" ]; then rm -R dist/; fi # Delete the dist/ folder if it exist
    - yarn
    - yarn build

# Deploy
Windows-Ready:
  tags:
    - main
  stage: deploy
  only:
    - production
  needs:
    - Prepare
    - Windows
  script:
    - cd /home/korbs/
    - wget -O artifact-windows.zip "https://korbsstudio.com/code/KorbsStudio/Penpot-Desktop/-/jobs/artifacts/main/download?job=Windows"
    - unzip artifact-windows.zip
    - cd artifact-windows
    - cp Penpot*.exe /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/$VERSION/
    - cp Penpot*.exe /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/latest/

Linux-Ready:
  tags:
    - main
  stage: deploy
  only:
    - production
  needs:
    - Prepare
    - Linux
  script:
    - cd dist/
    - cloudsmith push rpm korbsstudio/penpot-desktop/any-distro/any-version penpot-desktop*.rpm
    - cloudsmith push rpm korbsstudio/penpot-desktop/any-distro/any-version penpot-desktop*.deb