Prepare:
  tags:
    - main
  stage: .pre
  only:
    - production
  script:
    - if [ -d "dist/" ]; then rm -R dist/; fi # Delete the dist/ folder if it exist
    - export $(grep -v '^#' .env | xargs)
    - mkdir /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/$VERSION/

# Build
Windows:
  tags:
    - main
  stage: build
  only:
    - production
  script:
    - yarn
    - yarn build:win

Linux:
  tags:
    - main
  stage: build
  only:
    - production
  script:
    - yarn
    - yarn build

# Deploy
Windows-Ready:
  tags:
    - main
  stage: deploy
  only:
    - production
  needs:
    - job: Prepare
    - job: Windows
  script:
    - cp dist/Penpot*.exe /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/latest/
    - cp dist/latest.yml /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/latest/
    - cp dist/Penpot*.exe /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/$VERSION/

Linux-Ready:
  tags:
    - main
  stage: deploy
  only:
    - production
  needs:
    - job: Prepare
    - job: Linux
  script:
    - cd dist/
    - cloudsmith push rpm korbsstudio/penpot-desktop/any-distro/any-version penpot-desktop*.rpm
    - cloudsmith push rpm korbsstudio/penpot-desktop/any-distro/any-version penpot-desktop*.deb