# exe:
#   stage: build
#   script:
#     - echo "Do your build here"

prepare:
  stage: .pre
  script:
    - export $(grep -v '^#' .env | xargs)
    - mkdir /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/$VERSION/

deb:
  tags:
    - debian
  stage: build
  script:
    - echo "Get dependencies"
    - echo "Check dist/ directory"
    - echo "Run build"

rpm:
  stage: build
  script:
    - echo "Get dependencies"
    - echo "Check dist/ directory"
    - echo "Run build"

deb-ready:
  stage: deploy
  needs:
    - deb
    - prepare
  script:
    - echo "Prepare to upload..."
    - echo "Upload package to Cloudsmith..."
    - echo "Remove dist/ folder for future builds."

rpm-ready:
  stage: deploy
  needs:
    - rpm
    - prepare
  script:
    - echo "Prepare to upload..."
    - echo "Upload package to Cloudsmith..."
    - echo "Remove dist/ folder for future builds."
