Prepare:
  tags:
    - main
  stage: .pre
  only:
    - production
  script:
    - if [ -d "dist/" ]; then rm -R dist/; fi # Delete the dist/ folder if it exist
    - if [ -d "/korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/.prepare/*" ]; then rm /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/.prepare/*; fi
    - export $(grep -v '^#' .env | xargs)
    - mkdir /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/$VERSION/
    - yarn

# Build
Windows:
  tags:
    - main
  stage: build
  only:
    - production
  script:
    - yarn build:win
    - cp dist/Penpot*.exe /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/.prepare/
    - cp dist/latest.yml /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/.prepare/

Linux:
  tags:
    - main
  stage: build
  only:
    - production
  script:
    - yarn build
    - cp dist/*.deb /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/.prepare/
    - cp dist/*.rpm /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/.prepare/

# Deploy
Windows-Ready:
  tags:
    - main
  stage: deploy
  only:
    - production
  needs:
    - job: Prepare
    - job: Windows
  script:
    - cd /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/.prepare/
    - cp Penpot*.exe /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/latest/
    - cp latest.yml /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/latest/
    - cp Penpot*.exe /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/$VERSION/

Linux-Ready:
  tags:
    - main
  stage: deploy
  only:
    - production
  needs:
    - job: Prepare
    - job: Linux
  script:
    - cd /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/.prepare/
    - cloudsmith push rpm korbsstudio/penpot-desktop/any-distro/any-version *.rpm
    - cloudsmith push rpm korbsstudio/penpot-desktop/any-distro/any-version *.deb