# exe:
#   stage: build
#   script:
#     - echo "Do your build here"

Prepare:
  stage: .pre
  only:
    - production
  script:
    - export $(grep -v '^#' .env | xargs)
    - mkdir /korbs-studio-server/nginx/sites/releases/applications/penpot-desktop/$VERSION/

DEB:
  tags:
    - debian
  stage: build
  only:
    - production
  script:
    - echo "Get dependencies"
    - echo "Check dist/ directory"
    - echo "Run build"

RPM:
  stage: build
  only:
    - production
  script:
    - echo "Get dependencies"
    - echo "Check dist/ directory"
    - echo "Run build"

Debian-Ready:
  stage: deploy
  only:
    - production
  needs:
    - DEB
    - Prepare
  script:
    - echo "Prepare to upload..."
    - echo "Upload package to Cloudsmith..."
    - echo "Remove dist/ folder for future builds."

RHEL-Ready:
  stage: deploy
  only:
    - production
  needs:
    - RPM
    - Prepare
  script:
    - echo "Prepare to upload..."
    - echo "Upload package to Cloudsmith..."
    - echo "Remove dist/ folder for future builds."
